# Tasks Configuration

# Fire Expert Task (unchanged)
new_fire_expert_task:
  description: >
    Analyze the situation of the following fire emergency: {FireEmergency}.
    You must decide the roles of firefighters, the materials, and the vehicles needed for the firefighter crew to properly assess the fire incident.
    Reason about why each element is needed. Also, provide an approximate quantity for each element.
    The decision must be coherent. Do not include elements that are not useful for the specific case.
  expected_output: >
    You must indicate which firefighter roles, materials, and vehicles are necessary to assess the fire emergency.
    Indicate the approximate quantity needed for each element.
    Do not include the reasoning about why you select the elements; only provide a list.
  agent: new_fire_expert_agent

# Material Selector Task
material_select_task:
  description: >
    Using the output from the Fire Expert and considering the actual resources available at the station, adjust the plan to fit the resources.
    Identify any discrepancies between the ideal plan and available resources.
    Suggest additional resources needed if necessary and possible solutions.
  expected_output: >
    Provide an adjusted plan that aligns with the available resources.
    List any additional materials or equipment required that are not currently available.
    Ensure the adjusted plan is feasible with the current resources.
  agent: material_selector_agent

# Material Navigator Task
material_navigate_task:
  description: >
    Compute the optimal route from the fire station to the fire incident location specified in the emergency.
    Consider factors such as distance, traffic, and road conditions.
  expected_output: >
    Provide the route as a list of (X, Y) coordinates from the fire station to the fire incident location.
    Include the estimated response time to reach the incident location.
  agent: material_navigator_agent

# Firefighter Planner Task
firefighter_planner_task:
  description: >
    Combine the adjusted plans from the Material Selector and the route from the Material Navigator into a clear and coherent plan.
    Provide arguments for the decisions made.
    Ensure that the plan is actionable and efficient.
  expected_output: >
    A comprehensive plan detailing:
    - Personnel: roles and quantities.
    - Vehicles: types and quantities.
    - Materials: equipment and quantities.
    - Route to fire: list of (X, Y) coordinates.
    - Response time: estimated time to reach the fire incident location.
    Provide reasoning for the decisions made and ensure all elements are coherent.
  agent: firefighter_planner_agent
  # output_pydantic: FirefighterPlannerSchema