# Tasks Configuration

# Fire Expert Task (unchanged)
new_fire_expert_task:
  description: >
    Analyze the situation of the following fire emergency: {FireEmergency}.
    You must decide the roles of firefighters, the materials, and the vehicles needed for the firefighter crew to properly assess the fire incident.
    Reason about why each element is needed. Also, provide an approximate quantity for each element.
    The decision must be coherent. Do not include elements that are not useful for the specific case.
  expected_output: >
    You must indicate which firefighter roles, materials, and vehicles are necessary to assess the fire emergency.
    Indicate the approximate quantity needed for each element.
    Do not include the reasoning about why you select the elements; only provide a list.
    Include the address of the fire location!
  agent: new_fire_expert_agent

# Material Selector Task
material_select_task:
  description: >
    You are given:
    - The Fire Expert's recommendations (list of required firefighter roles, materials, and vehicles).
    - The list of actual resources available at the station (materials and vehicles).

    **Your Task:**
    1. Compare the Fire Expert's recommendations with the available resources.
    2. Adjust the plan to use only the resources we have.
    3. If some recommended items are not available, suggest alternatives from available resources.
    4. List any additional materials or equipment needed that are not currently available.
  expected_output: >
    Provide an adjusted plan that fits the resources we have, including:
    - Personnel: roles and quantities.
    - Vehicles: types and quantities.
    - Materials: equipment and quantities.
    All the items selected (personnel, vehicles and materials) must be available in the resources of the fire station.
    Ensure the adjusted plan is practical and feasible.
    Include the address of the fire location!
  agent: material_selector_agent

# Material Navigator Task
material_navigate_task:
  description: >
    **Your Task:**
    1. Receive the fire incident location coordinates.
    2. Use the FireCrewNavigatorTool to calculate the fastest and safest route from the fire station to the fire incident location.
    3. Consider factors such as distance, road conditions, and any known obstacles. Ensure the route is optimized for speed and safety.
    4. Estimate the response time to reach the incident location, knowing that you are traveling with trucks.
  expected_output: >
    Provide the route and response time.
    You MUST output a list of the streets and number included in the route to the fire and the estimated response time in minutes.
  agent: material_navigator_agent


# Firefighter Planner Task
firefighter_planner_task:
  description: >
    **Your Task:**
    1. Combine the adjusted plan from the Material Selector Agent (personnel, materials, vehicles) with the route and response time from the Material Navigator Agent.
    2. Create a comprehensive and coherent plan for the firefighting operation.
    3. Provide reasoning for the decisions made.
    4. Ensure that the plan is actionable, efficient, and practical.
  expected_output: >
    A detailed plan including:
    - **Personnel**: roles and quantities.
    - **Vehicles**: types and quantities.
    - **Materials**: equipment and quantities.
    - **Route to fire**: list of the streets to follow from the fire station to the fire location.
    - **Response time**: estimated time to reach the fire incident location.
    - **Reasoning**: explanations for the decisions made.
    Ensure all elements are coherent and the plan is feasible.
  agent: firefighter_planner_agent
