firefighter_divider_task:
  description: >
    Read a json file about the description of a fire incident and a json file about the resources available in the firefighter department.
    Determine the relevant information needed to make decisions about the type and number of firefighters.
    Determine the relevant information needed to make decisions about the equipment and types of vehicles.
  expected_output: >
    Two sets of information. 
    One set with the content involving the fire emergency context and firefighter personnel resources.
    Another set with the content involving the fire emergency context and the material and vehicles resources of the fire station.
  agent: firefighter_divider_agent

fire_expert_task:
  description: > 
    Analyse the situation of the fire incident.
    Answer the question: which roles and how many units are necessary to use in order to properly assess the fire incident. 
    Do not consider individual firefighters, treat each role as a group.
    You must provide an explanation about why a role is needed and how many units to include.
    Ensure you only include roles that are specifically needed for that fire emergency.
    Do not use a higher number of firefighters than the ones available per role.
    Do not use types of firefighter that are not in the firefighter station.
  expected_output: >
    You must indicate which firefighter roles are necessary to assess the fire emergency described, indicating for each one the quantity.
    For every role, add a very brief explanation about why is needed, defining what the firefighter would have to do to address the fire incident.
  agent: fire_expert_agent


material_select_task:
  description: >
    Based on the fire incident description and the available vehicles and equipment at the fire station, select the types and quantities of vehicles and equipment needed to address the fire.
    Ensure selections are within available resource limits.
  expected_output: >
    Provide a list of vehicles and equipment required to tackle the fire incident, including types and quantities for each.
  agent: material_selector_agent

material_navigate_task:
  description: >
    Calculate the optimal route for the selected vehicles to reach the fire incident location from the fire station.
    Consider factors like distance and travel time.
  expected_output: >
    Provide a route plan consisting of a list of (X, Y) coordinates from the fire station to the fire incident location, along with the estimated response time.
  agent: material_navigator_agent

material_plan_task:
  description: >
    Combine the selected vehicles and equipment with the calculated route to formulate a comprehensive material logistics plan.
  expected_output: >
    A unified plan detailing the vehicles and equipment to be deployed, the route to be taken, and the estimated response time.
  agent: material_planner_agent
  

firefighter_planner_task:
  description: > 
    You have a description of the personnel, equipment, and vehicles of a firefighter crew to address a fire incident.
    You also have the route to follow from the fire station to the fire and the total response time.
    You must create a plan to coordinate the firefighter actions to address the fire.
    Ensure that the information unified is coherent between personnel, equipment, and vehicles.
    If you think some elements are missing to properly address the fire, you can add additional information, but only if it is extremely necessary.


firefighter_planner_task:
  description: > 
    Create a plan to coordinate the firefighter actions to address the fire.
    Ensure that the information unified is coherent between personnel, equipment, and vehicles. 
    Make sure to not include additional elements that are not specified in the information.
  expected_output: >
    A single unified plan for the firefighter crew that includes the personnel needed, the equipment and vehicles to bring to address the fire, the route that must be followed, and the total response time.
  agent: firefighter_planner_agent