firefighter_divider_task:
  description: >
    You will receive a description about a fire incident and the resources available in the firefighter department.
    Your goal is to divide that content into two groups. One must contain the relevant information
    to select the type and the number of firefighters needed. The other must include the relevant 
    information to be able to select the equipment and type of vehicles needed.
  expected_output: >
    Two sets of data.
      1) The subset of information relevant to select the personal needed.
      2) The subset of information relevant to select the material and vehicles needed.
  agent: firefigther_divider_agent