distill_task:
  description: >
    Extract information from the call transcript provided in the file related to:
      1. Severity of the fire (light, moderate, severe, extreme).
      2. Type of fire (ordinary, electrical, gas, chemical or other types).
      3. Location of the emergency.
      4. How many people are injured. Count ONLY injured people.
      5. How bad severe the injuries of each person.
  expected_output: >
    A concise yet accurate list of bullet-points with the requested information 
    following schema: {DistilledEmergencyCallSchema.get_schema()}
  agent: distiller_agent

divide_task:
  description: >
    You are going to receive information that describes an emergency situation, and 
    your task is to divide such information into two, one should contain relevant 
    information for the fire department and the other relevant information for the 
    medical department.
  expected_output: >
    The input information split in two: on the one hand information for the fire 
    department and on the other information for the medical department. 
    Follow the schema {DividedInformationSchema.get_schema()}.
  agent: divider_agent