distill_task:
  description: >
    Extract information from the call transcript provided in the file related to:
      1. Severity of the fire (light, moderate, severe, extreme).
      2. Type of fire (ordinary, electrical, gas, chemical or other types).
      3. Location of the emergency.
      4. How many people are injured. Count ONLY injured people.
      5. How bad severe the injuries of each person.
  expected_output: >
    A concise yet accurate list of bullet-points with the requested information 
    following schema: {DistilledEmergencyCallSchema.get_schema()}
  agent: distiller_agent
