medical_divide_task:
  description: >
    You will receive information describing a medical-related emergency. 
    Your goal is to split the data into two branches: one for the ambulance-focused 
    details (e.g., how many victims, needed emergency transport, etc.) and another 
    for hospital-focused details (e.g., patient capacity, facility availability). 
    Organize the information so each branch has only what it needs to proceed.
  expected_output: >
    Two sets of data: 
      1) The subset of emergency information relevant to the ambulance branch.
      2) The subset relevant to the hospital branch. 
    Make sure to keep each subset self-contained and clearly labeled for its destination.
  agent: medical_divider_agent

ambulance_select_task:
  description: >
    Analyze the emergency details and decide how many ambulances are required, 
    taking into account their availability, proximity, and capacity to handle the 
    current situation. Provide identifiers or references for the chosen ambulances.
  expected_output: >
    For each injured person (identified by their ID), assign them to an ambulance ID. 
    Additionally, associate the IDs of the nurses and pilots responsible for that 
    ambulance with the same ambulance ID.
  agent: ambulance_selector_agent

ambulance_navigate_task:
  description: >
    Determine the optimal routes for each selected ambulance to travel from their 
    current location(s) to the emergency site. Base your route planning on minimal 
    travel time.
  expected_output: >
    A mapping of each ambulance identification to a route plan.
  agent: ambulance_navigator_agent

ambulance_plan_task:
  description: >
    Combine the outputs from the Ambulance Selector and Ambulance Navigator. 
    Produce a unified ambulance plan that specifies which ambulances are assigned 
    and the route each will follow. This plan is then passed along to the next stage.
  expected_output: >
    A single, consolidated plan detailing each selected ambulance, its route, 
    and any additional notes or requirements needed by the ambulance teams.
  agent: ambulance_planner_agent

hospital_select_task:
  description: >
    Assess the available hospital options and choose the most suitable facilities 
    for treating the victims. Take into account critical factors such as the hospital's 
    capacity, specialized medical services, and proximity to the emergency site to 
    ensure timely and effective care.
  expected_output: >
    For all the injured persons, assign them to the hospital nearest hospital, taking
    into account the available capacity and the severity of their injuries, meaning that
    UCI patients should be assigned to UCI hospitals, and so on.
  agent: hospital_selector_agent

hospital_navigate_task:
  description: >
    Plan the route from the emergency location to the selected hospital(s), 
    aiming for minimal travel time and safe transport of the injured. If 
    multiple hospitals are chosen, provide separate route plans for each.
  expected_output: >
    A set of route plans—one per hospital IDs assignment—specifying the chosen 
    path or key checkpoints for each patient injured (IDs) that needs to go to
    the hospital.
  agent: hospital_navigator_agent

hospital_plan_task:
  description: >
    Synthesize the outputs from the Hospital Selector and Hospital Navigator 
    into a comprehensive hospital plan. Include which hospitals are chosen, 
    and how each ambulance will reach them.
  expected_output: >
    A consolidated view of hospital usage, highlighting each hospital, 
    assigned patients/ambulances, and the routes to be followed.
  agent: hospital_planner_agent

medical_plan_task:
  description: >
    Produce the final medical plan by aggregating the outputs from both 
    the Ambulance branch and the Hospital branch. Ensure a coherent, end-to-end 
    proposal from dispatch to final patient handoff. 
  expected_output: >
    A single unified plan for the Medical Services Crew that includes ambulance 
    assignments, hospital assignments, and any relevant route or timing 
    information.
  agent: medical_planner_agent
