emergency_doctor_task:
  description: >
    First, use the FileReadTool to read information about the fire emergency.
    Second, evaluate the severity of each injured people and classify their injury 
    in one of the following categories: "Nurse Check", "Hospitalization" and "ICU".
    Nurse check means that being attended by the ambulance nurses is sufficient.
    Hospital Check means that they need to go to the hospital, but not ICU.
    ICU means they need Intensive Care Unit (ICU) because they are very damaged.
  expected_output: >
    You MUST use the following output structure:
    """
    Injured {injured_id1}
    - Injury: {State their injury}
    - Requires {Nurse Check/Hospitalization/ICU}

    Injured {injured_id2}
    - Injury: {State their injury}
    - Requires {Nurse Check/Hospitalization/ICU}
    ...
    """
  agent: emergency_doctor_agent

ambulance_select_task:
  description: >
    First, decide how many ambulances are required for the fire emergency. Then, obtain the location
    of the fire emergency. Then, obtain the location of all ambulances, you must use again the FileReadTool to obtain a new result.
    Then, once you have all ambulances locations, you MUST use the RouteDistanceCalculator tool passing TWO parameters: 
    the first parameter is a string containing the location of the ambulance, and the second parameter is a string containing 
    the location of the fire emergency. Keep the distance from each ambulance to the fire emergency. Then,
    select the closest ambulances to send to the fire emergency, given the number of ambulances you decided earlier.
    Assign to each ambulance one pilot and one nurse, providing their ids. No pilot, ambulance and nurse can be repeated.
  expected_output: >
    For each injured person (use their ID to identify them), assign them to an ambulance ID.
    Additionally, for each ambulance, provide IDs of the nurse and pilot that go to that ambulace.
    For example:
    """
    Injured {injured_id}:
      - Ambulance Assigned: {ambulance_id}
      - Pilot Assigned: {pilot_id}
      - Nurse Assigned: {nurse_id}
    """
  agent: ambulance_selector_agent

ambulance_navigate_task:
  description: >
    Determine the optimal routes for each selected ambulance to travel from their 
    current location(s) to the emergency site. Base your route planning on minimal 
    travel time.
  expected_output: >
    A mapping of each ambulance identification to a route plan.
  agent: ambulance_navigator_agent

ambulance_plan_task:
  description: >
    Combine the outputs from the Ambulance Selector and Ambulance Navigator. 
    Produce a unified ambulance plan that specifies which ambulances are assigned 
    and the route each will follow. This plan is then passed along to the next stage.
  expected_output: >
    A single, consolidated plan detailing each selected ambulance, its route, 
    and any additional notes or requirements needed by the ambulance teams.
  agent: ambulance_planner_agent

hospital_select_task:
  description: >
    Assess the available hospital options and choose the most suitable facilities 
    for treating the victims. Take into account critical factors such as the hospital's 
    capacity, specialized medical services, and proximity to the emergency site to 
    ensure timely and effective care.
  expected_output: >
    For all the injured persons, assign them to the hospital nearest hospital, taking
    into account the available capacity and the severity of their injuries.
  agent: hospital_selector_agent

hospital_navigate_task:
  description: >
    Plan the route from the emergency location to the selected hospital(s), 
    aiming for minimal travel time and safe transport of the injured. If 
    multiple hospitals are chosen, provide separate route plans for each.
  expected_output: >
    A set of route plans—one per hospital IDs assignment—specifying the chosen 
    path or key checkpoints for each patient injured (IDs) that needs to go to
    the hospital.
  agent: hospital_navigator_agent

hospital_plan_task:
  description: >
    Synthesize the outputs from the Hospital Selector and Hospital Navigator 
    into a comprehensive hospital plan. Include which hospitals are chosen, 
    and how each ambulance will reach them.
  expected_output: >
    A consolidated view of hospital usage, highlighting each hospital, 
    assigned patients/ambulances, and the routes to be followed.
  agent: hospital_planner_agent

medical_plan_task:
  description: >
    Produce the final medical plan by aggregating the outputs from both 
    the Ambulance branch and the Hospital branch. Ensure a coherent, end-to-end 
    proposal from dispatch to final patient handoff. 
  expected_output: >
    A single unified plan for the Medical Services Crew that includes ambulance 
    assignments, hospital assignments, and any relevant route or timing 
    information.
  agent: medical_planner_agent
