medical_divide_task:
  description: >
    You will receive a JSON with some emergency information. 
    Your goal is to split the data into two branches: one for the ambulance-focused 
    details, which is basicaly the emergency location, how many injured people are 
    and another branch for hospital-focused how many people are injured and how severe 
    are their injuries and also the emergency location.
    Organize the information so each branch has only what it needs to proceed.
  expected_output: >
    Two sets of data: 
      1) The subset of emergency information relevant to the ambulance branch.
        1.1) The emergency location.
        1.2) The number of injured people and IDs.
      2) The subset relevant to the hospital branch. 
        2,1) The emergency location.
        2.2) The number of injured people and IDs.
        2.3) Extra information per IDs or what happened to them.
    Make sure to keep each subset self-contained and clearly labeled for its destination.
  agent: medical_divider_agent

emergency_doctor_task:
  description: >
    You will receive information about some emergency with information of the
    hurted people. Evaluate the severity of each patient's injuries and determine 
    the appropriate level of care needed for each individual. You have to classify
    every patient in one of the following categories: Nurse Check, Hospitalization 
    and ICU. Nurse check means that will be attended by the ambulance nurses and it
    should be sufficient. Hospital Check is that they need to go to the hospital to
    do more checks or to be hospitalized but not ICU. Finally, ICU is that they need 
    to stay in the Intensive Care Unit (ICU) because they are very damaged.
  expected_output: >
    For each injured person (identified by their ID), evaluate the 
    severity of their injuries and classify them to the level of care they require. 
    Those are Nurse Check, Hospitalization, and ICU.
  agent: emergency_doctor_agent

ambulance_select_task:
  description: >
    Analyze the emergency details and decide how many ambulances are required and also
    the personal they need to go to the emergency. Take intro account that all the people
    that need hospitalization or ICU should have one ambulance assigned to them. For the
    people that only require a nurse check, they can be assigned to the same ambulance, but
    take in to account that no more than 3 people can be assigned to the same ambulance, so in
    case we have more than 3 people that only require a nurse check, we will need to assign
    more ambulances, respecting the limit.
  expected_output: >
    For each injured person (identified by their ID), assign them to an ambulance ID. 
    Additionally, associate the IDs of the nurses and pilots responsible for that 
    ambulance with the same ambulance ID.
  agent: ambulance_selector_agent

ambulance_navigate_task:
  description: >
    Determine the optimal routes for each selected ambulance to travel from their 
    current location(s) to the emergency site. Base your route planning on minimal 
    travel time.
  expected_output: >
    A mapping of each ambulance identification to a route plan.
  agent: ambulance_navigator_agent

ambulance_plan_task:
  description: >
    Combine the outputs from the Ambulance Selector and Ambulance Navigator. 
    Produce a unified ambulance plan that specifies which ambulances are assigned 
    and the route each will follow. This plan is then passed along to the next stage.
  expected_output: >
    A single, consolidated plan detailing each selected ambulance, its route, 
    and any additional notes or requirements needed by the ambulance teams.
  agent: ambulance_planner_agent

hospital_select_task:
  description: >
    Assess the available hospital options and choose the most suitable facilities 
    for treating the victims. Take into account critical factors such as the hospital's 
    capacity, specialized medical services, and proximity to the emergency site to 
    ensure timely and effective care.
  expected_output: >
    For all the injured persons, assign them to the hospital nearest hospital, taking
    into account the available capacity and the severity of their injuries.
  agent: hospital_selector_agent

hospital_navigate_task:
  description: >
    Plan the route from the emergency location to the selected hospital(s), 
    aiming for minimal travel time and safe transport of the injured. If 
    multiple hospitals are chosen, provide separate route plans for each.
  expected_output: >
    A set of route plans—one per hospital IDs assignment—specifying the chosen 
    path or key checkpoints for each patient injured (IDs) that needs to go to
    the hospital.
  agent: hospital_navigator_agent

hospital_plan_task:
  description: >
    Synthesize the outputs from the Hospital Selector and Hospital Navigator 
    into a comprehensive hospital plan. Include which hospitals are chosen, 
    and how each ambulance will reach them.
  expected_output: >
    A consolidated view of hospital usage, highlighting each hospital, 
    assigned patients/ambulances, and the routes to be followed.
  agent: hospital_planner_agent

medical_plan_task:
  description: >
    Produce the final medical plan by aggregating the outputs from both 
    the Ambulance branch and the Hospital branch. Ensure a coherent, end-to-end 
    proposal from dispatch to final patient handoff. 
  expected_output: >
    A single unified plan for the Medical Services Crew that includes ambulance 
    assignments, hospital assignments, and any relevant route or timing 
    information.
  agent: medical_planner_agent
